version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app  # Mount the current directory to /app in the container
    ports:
      - "8000:8000"  # Map port 8000 on the host to port 8000 in the container
    environment:
      - DATABASE_URL=postgresql://db_user:db_password@db:5432/my_database
      - SECRET_KEY=your_secret_key
      - DEBUG=True
    depends_on:
      - db

  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: my_database
      POSTGRES_USER: db_user
      POSTGRES_PASSWORD: db_password
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
